# Numpy Pandas Assignment

### Task 1: NumPy Basics

#### Array Creation

In [4]:
# Creating 1D and 2D array

# 1D
import numpy as np
my_1d=np.array([1,2,4,5,6])
my_1d

array([1, 2, 4, 5, 6])

In [6]:
# 2D array

my_2d=np.array([[2,3,4],[3,5,6],[5,7,4]])
my_2d
print('2D Array:\n',my_2d)

2D Array:
 [[2 3 4]
 [3 5 6]
 [5 7 4]]


#### Array Operations

In [7]:
# performing basic operations in array
my_1d_add=my_1d+12
my_2d_add=my_2d+20
my_2d_mul=my_2d*2

print('1D array addition operation:\n',my_1d_add)
print('2D array addition operation:\n',my_2d_add)
print('2D array multiplication operation:\n',my_2d_mul)

1D array addition operation:
 [13 14 16 17 18]
2D array addition operation:
 [[22 23 24]
 [23 25 26]
 [25 27 24]]
2D array multiplication operation:
 [[ 4  6  8]
 [ 6 10 12]
 [10 14  8]]


#### indexing and Slicing

In [12]:
# Demonstrate indexing and slicing on the array
my_1d_array_index=my_1d[3]  # indexing on the array
print(my_1d_array_index)

my_2d_array_index=my_2d[1,2] #indexing of 2D array
print(my_2d_array_index)

#Slicing on array

my_2d_slice=my_2d[:2,1:3] #select row from begining upto index 2(excluding 2) and columns from index 1 upto 3 (not including)
print('2d slice:\n',my_2d_slice)

my_1d_slice=my_1d[1:2]
print('1D Array slice:\n',my_1d_slice)



5
6
2d slice:
 [[3 4]
 [5 6]]
1D Array slice:
 [2]


#### Shape and Reshape

In [27]:
# Show how to check the shape of an array and reshape it

print('Shape of 2D array : ',my_2d.shape)
reshape_array_2d=my_2d.reshape(9,1)

print('Reshape of 2D array:\n',reshape_array_2d)

Shape of 2D array :  (3, 3)
Reshape of 2D array:
 [[2]
 [3]
 [4]
 [3]
 [5]
 [6]
 [5]
 [7]
 [4]]
