# Numpy Pandas Assignment

### Task 1: NumPy Basics

#### Array Creation

In [4]:
# Creating 1D and 2D array

# 1D
import numpy as np
my_1d=np.array([1,2,4,5,6])
my_1d

array([1, 2, 4, 5, 6])

In [6]:
# 2D array

my_2d=np.array([[2,3,4],[3,5,6],[5,7,4]])
my_2d
print('2D Array:\n',my_2d)

2D Array:
 [[2 3 4]
 [3 5 6]
 [5 7 4]]


#### Array Operations

In [7]:
# performing basic operations in array
my_1d_add=my_1d+12
my_2d_add=my_2d+20
my_2d_mul=my_2d*2

print('1D array addition operation:\n',my_1d_add)
print('2D array addition operation:\n',my_2d_add)
print('2D array multiplication operation:\n',my_2d_mul)

1D array addition operation:
 [13 14 16 17 18]
2D array addition operation:
 [[22 23 24]
 [23 25 26]
 [25 27 24]]
2D array multiplication operation:
 [[ 4  6  8]
 [ 6 10 12]
 [10 14  8]]
